#!/usr/bin/env python2.7

# load default python packages
import logging, optparse, sys
from os.path import *

# add <scriptDir>/lib/ to package search path
sys.path.insert(0, join(dirname(abspath(__file__)), "lib"))

import pubGeneric, pubExpMatrix, pubConf

def main(args, options):
    datasetStr, pmidListFname, outBase = args
    dirNames = pubGeneric.resolveDatasetDesc(datasetStr)
    pubGeneric.setupLogging("", options)
    wordListFname = options.wordList
    pubExpMatrix.exportMatrix(dirNames, pmidListFname, outBase, wordListFname, options.skipMap)

# === COMMAND LINE INTERFACE, OPTIONS AND HELP ===
parser = optparse.OptionParser("""usage: %prog [options] datasets pmidFile outBasename - create a matrix for mallet""")

parser.add_option("-d", "--debug", dest="debug", action="store_true", help="show debug messages")
parser.add_option("-v", "--verbose", dest="verbose", action="store_true", help="show more debug messages")
parser.add_option("", "--skipMap", dest="skipMap", action="store_true", help="skip map step")
parser.add_option("-s", "--wordList", dest="wordList", action="store", help="optional list of words to use, one per line")
(options, args) = parser.parse_args()

if args==[]:
    parser.print_help()
    exit(1)

main(args, options)
