#!/usr/bin/env python2.7

# preprocess a dictionary in the format
# <id>tab<term> to a gzipped marshalled
# file for the fastFind.py module

import fastFind, gzip, marshal, logging, sys
from os.path import *

logging.basicConfig(level=logging.INFO)

logging.info("preprocessing dict")
dictFname = sys.argv[1]

fastFind.prepDict(dictFname)

logging.info("written preprocessed dict to %s" % fname)
